In [2]:
import pandas as pd
from pandas import Series,DataFrame
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [4]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [9]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
#obj2
obj2['a']
obj2[['c', 'a', 'd']]

c    3
a   -5
d    4
dtype: int64

In [10]:
import numpy as np
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [11]:
'b' in obj2

True

In [12]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 
'Utah': 5000}
obj3=pd.Series(sdata)

In [13]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [14]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [16]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [18]:
obj3+obj4  #自动对齐

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [19]:
obj4.name = 'population'  #Series 本身的Name 属性 和索引的name 属性
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

0    4
1    7
2   -5
3    3
dtype: int64

In [21]:
obj.index=['w','g','d','a']  #索引修改
obj

w    4
g    7
d   -5
a    3
dtype: int64

In [22]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 
'Nevada'], 
 'year': [2000, 2001, 2002, 2001, 2002, 2003], 
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]} 
frame = pd.DataFrame(data)

In [23]:
frame  #表格 

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [24]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [25]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])  # 按指定列显示

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [31]:
frame2 = pd.DataFrame(data, columns=['year','state', 'pop', 'debt'],index=['one', 'two', 'three', 'four','five', 'six'])      
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [32]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [33]:
frame2['state'] #获取列 得到一个Series

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [34]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [35]:
frame2.loc['three']  #获取行 

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [36]:
frame2['debt'] = np.arange(6.)#修改列值

In [37]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [38]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2.debt=val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [39]:
frame2['eastern'] = frame2.state == 'Ohio'#为不存在列赋值会创建新列

In [40]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [41]:
del frame2['eastern']#del 删除列

In [42]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [45]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}} #嵌套字典
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [46]:
frame3 = pd.DataFrame(pop)  #外层字典的键作为列，内层键则作为行索引
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [47]:
frame3.T #转置

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [48]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [49]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [50]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [51]:
frame3.columns  #列标签

Index(['Nevada', 'Ohio'], dtype='object')

In [52]:
frame3.index   #行标签

Int64Index([2000, 2001, 2002], dtype='int64')

In [53]:
2002 in frame3.index

True

In [54]:
obj  #pandas 对象的一个重要方法是 reindex，其作用是创建一个新对象，它的数据符合新的索引

w    4
g    7
d   -5
a    3
dtype: int64

In [56]:
 obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [57]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [58]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)), 
 ....: index=['a', 'c', 'd'], 
 ....: columns=['Ohio', 'Texas', 
'California'])

In [59]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [60]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [61]:
states = ['Texas', 'Utah', 'California']  #列修改
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [62]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [64]:
new_obj = obj.drop('c') #丢弃指定轴上的项
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [68]:
frame2.drop('c')  #但是fame2 不会改变

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
d   6.0    7.0         8.0

In [75]:
frame2.drop('Texas',axis=1) #axis=1 或 axis='columns'可以删除列的值
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [76]:
obj[1]  #索引

1.0

In [78]:
obj['b'] #索引

1.0

In [79]:
obj[obj < 2] #返回前两个

a    0.0
b    1.0
dtype: float64

In [80]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [92]:
frame2[['Ohio','Texas']] #获取列

Ohio  Texas
a   0.0    1.0
b   NaN    NaN
c   3.0    4.0
d   6.0    7.0

In [85]:
frame2.loc['c']  #获取行

Ohio          3.0
Texas         4.0
California    5.0
Name: c, dtype: float64

In [90]:
frame2[:1] #获取行

Ohio  Texas  California
a   0.0    1.0         2.0

In [98]:
ser2 = pd.Series(np.arange(3.), index=[0, 1, 2])
ser2[-1]

2.0

In [101]:
ser = pd.Series(np.arange(3.))
ser[:1]

0    0.0
dtype: float64

In [102]:
ser.loc[:1] #按标签查

0    0.0
1    1.0
dtype: float64

In [103]:
ser.iloc[:1]

0    0.0
dtype: float64

In [104]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],index=['a', 'c', 'e', 'f', 'g'])
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [105]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [107]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.sort_index()

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [108]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64